In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics

In [2]:
datab=pd.read_excel(r'C:\Users\Lab4PC17\Desktop\New folder\bill_authentication.xlsx')
datab.head()

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [3]:
X=datab[['Variance','Skewness','Curtosis','Entropy']].values
Y=datab['Class'].values
Xtr,Xte,Ytr,Yte=train_test_split(X,Y,test_size=0.2,random_state=0)

In [4]:
svcc=SVC(kernel='linear')
svcc.fit(Xtr,Ytr)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [5]:
Ypr=svcc.predict(Xte)
df = pd.DataFrame({'Actual': Yte.flatten(), 'Predicted': Ypr.flatten()})
df

     Actual  Predicted
0         1          1
1         0          0
2         1          1
3         0          0
4         0          0
5         0          0
6         0          0
7         0          0
8         1          1
9         1          1
10        0          0
11        0          0
12        1          1
13        0          0
14        0          0
15        0          0
16        1          1
17        1          1
18        0          0
19        0          0
20        1          1
21        0          0
22        0          0
23        1          1
24        0          0
25        1          1
26        0          0
27        1          1
28        0          0
29        0          0
..      ...        ...
245       0          0
246       0          0
247       0          0
248       0          0
249       0          0
250       0          0
251       1          1
252       0          0
253       1          1
254       1          1
255       0          0
256       0          0
257       1          1
258       1          1
259       1          1
260       0          0
261       0          0
262       0          0
263       1          1
264       0          0
265       0          0
266       1          1
267       1          1
268       0          0
269       1          1
270       1          1
271       0          0
272       1          1
273       1          1
274       1          1

[275 rows x 2 columns]

In [11]:
print(metrics.accuracy_score(Yte,Ypr))
print(metrics.precision_score(Yte,Ypr))
print(metrics.recall_score(Yte,Ypr))

0.9927272727272727
0.9833333333333333
1.0